name: sirwash
description: A new Flutter project.

publish_to: 'none'

version: 2.3.2

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  android_path_provider: ^0.3.0
  animate_do: ^3.0.2
  animated_theme_switcher: ^2.0.5
  awesome_dialog: ^3.0.2
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.4
  device_info_plus: ^3.2.3
  device_preview: ^1.1.0
  dio: ^4.0.0
  dotted_border: ^2.0.0+2
  dropdown_search: 5.0.5
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.3
  flutter_localizations:
    sdk: flutter
  flutter_osm_plugin: ^0.42.0
  flutter_svg: ^1.1.3
  flutter_zoom_drawer: ^2.1.1
  formz: ^0.6.0
  freezed_annotation: ^2.0.3
  geolocator: ^7.0.3
  get: ^4.6.5
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  jwt_decoder: ^2.0.1
  location: ^4.4.0
  logger: ^1.1.0
  lottie: ^1.2.2
  mapsforge_flutter: ^2.0.2
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.2.0-beta-1
  skeleton_text: ^3.0.0
  slide_to_act: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon/app-icon.jpg"
  adaptive_icon_foreground: "assets/appicon/app-foreground.png"
  adaptive_icon_background: "assets/appicon/app-background.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true

  assets:
    - assets/appicon/
    - assets/data/
    - assets/icons/
    - assets/img/
    - assets/lottie/
    - assets/files/
    # Offline maps
    - assets/maps/render_themes/
    - assets/maps/icons/
    # Mandatory for Mapsforge lib
    - packages/mapsforge_flutter/assets/patterns/dark_farmland.svg
    - packages/mapsforge_flutter/assets/patterns/dark_military.png
    - packages/mapsforge_flutter/assets/patterns/coniferous.svg
    - packages/mapsforge_flutter/assets/patterns/coniferous_and_deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/farmland.svg
    - packages/mapsforge_flutter/assets/patterns/grass.svg
    - packages/mapsforge_flutter/assets/patterns/hills.svg
    - packages/mapsforge_flutter/assets/patterns/quarry.svg
    - packages/mapsforge_flutter/assets/patterns/scrub.svg
    - packages/mapsforge_flutter/assets/patterns/swamp.svg
    - packages/mapsforge_flutter/assets/patterns/access-destination.png
    - packages/mapsforge_flutter/assets/patterns/access-private.png
    - packages/mapsforge_flutter/assets/patterns/arrow.png
    - packages/mapsforge_flutter/assets/patterns/cemetery.png
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/dot.png
    - packages/mapsforge_flutter/assets/patterns/farmland.svg
    - packages/mapsforge_flutter/assets/patterns/grass.svg
    - packages/mapsforge_flutter/assets/patterns/hills.svg
    - packages/mapsforge_flutter/assets/patterns/marsh.png
    - packages/mapsforge_flutter/assets/patterns/military.png
    - packages/mapsforge_flutter/assets/patterns/nature-reserve.png
    - packages/mapsforge_flutter/assets/patterns/pike.png
    - packages/mapsforge_flutter/assets/patterns/quarry.svg
    - packages/mapsforge_flutter/assets/patterns/rail.png
    - packages/mapsforge_flutter/assets/patterns/scrub.svg
    - packages/mapsforge_flutter/assets/patterns/swamp.svg
    - packages/mapsforge_flutter/assets/patterns/wood-coniferous.png
    - packages/mapsforge_flutter/assets/patterns/wood-deciduous.png
    - packages/mapsforge_flutter/assets/patterns/wood-mixed.png
    - packages/mapsforge_flutter/assets/symbols/bench.svg
    - packages/mapsforge_flutter/assets/symbols/cable_car.svg
    - packages/mapsforge_flutter/assets/symbols/chair_lift.svg
    - packages/mapsforge_flutter/assets/symbols/dot_black.svg
    - packages/mapsforge_flutter/assets/symbols/dot_blue.svg
    - packages/mapsforge_flutter/assets/symbols/dot_blue_dark.svg
    - packages/mapsforge_flutter/assets/symbols/dot_magenta.svg
    - packages/mapsforge_flutter/assets/symbols/dot_white.svg
    - packages/mapsforge_flutter/assets/symbols/gondola.svg
    - packages/mapsforge_flutter/assets/symbols/oneway.svg
    - packages/mapsforge_flutter/assets/symbols/peak.svg
    - packages/mapsforge_flutter/assets/symbols/railway-crossing-small.svg
    - packages/mapsforge_flutter/assets/symbols/railway-crossing.svg
    - packages/mapsforge_flutter/assets/symbols/traffic_signal.svg
    - packages/mapsforge_flutter/assets/symbols/volcano.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/alpinehut.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/camping.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/caravan_park.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/chalet.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/hostel.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/hotel2.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/shelter2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/firestation3.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/fountain2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/library.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/playground.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/police2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/post_box.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/post_office.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/recycling.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/telephone.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/toilets.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/blocks.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/bollard.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/cycle_barrier.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/gate.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/lift_gate.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/stile.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/fountain2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/library.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/toilets.svg
    - packages/mapsforge_flutter/assets/symbols/custom/money/atm2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/archaeological2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/attraction.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/castle2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/cinema2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/information.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/memorial.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/monument.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/museum.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/ruin.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/theatre.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/view_point.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/windmill.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/zoo.svg
    - packages/mapsforge_flutter/assets/symbols/education/nursery3.svg
    - packages/mapsforge_flutter/assets/symbols/education/school.svg
    - packages/mapsforge_flutter/assets/symbols/education/university.svg
    - packages/mapsforge_flutter/assets/symbols/food/bar.svg
    - packages/mapsforge_flutter/assets/symbols/food/biergarten.svg
    - packages/mapsforge_flutter/assets/symbols/food/cafe.svg
    - packages/mapsforge_flutter/assets/symbols/food/drinkingtap.svg
    - packages/mapsforge_flutter/assets/symbols/food/fastfood.svg
    - packages/mapsforge_flutter/assets/symbols/food/pub.svg
    - packages/mapsforge_flutter/assets/symbols/food/restaurant.svg
    - packages/mapsforge_flutter/assets/symbols/health/doctors2.svg
    - packages/mapsforge_flutter/assets/symbols/health/hospital.svg
    - packages/mapsforge_flutter/assets/symbols/health/pharmacy.svg
    - packages/mapsforge_flutter/assets/symbols/money/atm2.svg
    - packages/mapsforge_flutter/assets/symbols/money/bank2.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/buddhist.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/christian.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/hindu.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/islamic.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/jewish.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/shinto.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/unknown.svg
    - packages/mapsforge_flutter/assets/symbols/poi/cave.svg
    - packages/mapsforge_flutter/assets/symbols/poi/embassy2.svg
    - packages/mapsforge_flutter/assets/symbols/poi/mountain_pass.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/alcohol.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/bakery.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/bicycle.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/book.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/butcher.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/car_repair.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/convenience.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/diy.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/greengrocer.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/laundrette.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/marketplace.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/supermarket.svg
    - packages/mapsforge_flutter/assets/symbols/sport/golf.svg
    - packages/mapsforge_flutter/assets/symbols/sport/shooting.svg
    - packages/mapsforge_flutter/assets/symbols/sport/soccer.svg
    - packages/mapsforge_flutter/assets/symbols/sport/stadium.svg
    - packages/mapsforge_flutter/assets/symbols/sport/swimming_outdoor.svg
    - packages/mapsforge_flutter/assets/symbols/sport/tennis.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/archaeological2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/attraction.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/castle2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/cinema2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/information.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/memorial.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/monument.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/museum.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/picnic.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/ruin.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/theatre.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/view_point.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/windmill.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/zoo.svg
    - packages/mapsforge_flutter/assets/symbols/transport/airport2.svg
    - packages/mapsforge_flutter/assets/symbols/transport/bus_station.svg
    - packages/mapsforge_flutter/assets/symbols/transport/bus_stop.svg
    - packages/mapsforge_flutter/assets/symbols/transport/fuel.svg
    - packages/mapsforge_flutter/assets/symbols/transport/helicopter.svg
    - packages/mapsforge_flutter/assets/symbols/transport/lighthouse.svg
    - packages/mapsforge_flutter/assets/symbols/transport/parking.svg
    - packages/mapsforge_flutter/assets/symbols/transport/parking_private.svg
    - packages/mapsforge_flutter/assets/symbols/transport/rental_bicycle.svg
    - packages/mapsforge_flutter/assets/symbols/transport/slipway.svg
    - packages/mapsforge_flutter/assets/symbols/transport/traffic_lights.svg
    - packages/mapsforge_flutter/assets/symbols/transport/train_station2.svg
    - packages/mapsforge_flutter/assets/symbols/transport/tram_stop.svg
    - packages/mapsforge_flutter/assets/symbols/water/weir.svg
    - packages/mapsforge_flutter/assets/symbols/windsock.svg
    - packages/mapsforge_flutter/assets/symbols/viewpoint.svg

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
