import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:archive/archive.dart';
import 'package:date_format/date_format.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:geolocator/geolocator.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;
// import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:logger/logger.dart';
import 'package:path_provider/path_provider.dart';
import 'package:rxdart/rxdart.dart';
import 'package:sirwash/data/models/models.dart';
import 'package:sirwash/modules/misc/error/misc_error_controller.dart';
import 'package:sirwash/routes/app_pages.dart';
import 'package:sirwash/themes/ak_ui.dart';
import 'package:sirwash/widgets/widgets.dart';

part 'api_exception.dart';
part 'app_catcher.dart';
part 'business_exception.dart';
part 'date_time_functions.dart';
part 'dio_client.dart';
part 'extensions.dart';
part 'filemgr.dart';
part 'geolocator_helpers.dart';
part 'helpers.dart';
part 'network_exceptions.dart';
part 'number_format.dart';
part 'numerical_range_formatter.dart';
part 'pathhandler.dart';
part 'transparent_image.dart';
part 'try_catch.dart';
part 'wrapper.dart';
